### ISSUE TITLE
Question: What are the differences between this and the Firefox GNOME theme?

### ISSUE THREAD

**Issue by echosa** [Blackrucat/firefox_gnome_theme-Pop_OS#1]
I'm curious what the differences are between this theme and https://github.com/rafaelmardojai/firefox-gnome-theme

Both look nice, but both look very similar. I'm currently using the other one, and I'd like to know the differences between the two to decide if I would like to switch to this one. It seems that @rafaelmardojai worked on both, so perhaps they are the best qualified to answer. :-) Thanks!

**Comment by rafaelmardojai** [comment]
This looks like a fork of my theme with some changes from https://github.com/rafaelmardojai/firefox-gnome-theme/pull/173 applied. My theme was made exclusively for Adwaita, but recently I'm accepting giving support to thirdparty GTK themes. The PR mentioned is adding support for PopOS theme, but we haven't find the time to finish it.

If you want a Firefox PopOS theme, I will recommend you to use this one until we get to merge https://github.com/rafaelmardojai/firefox-gnome-theme/pull/173.

Regards!

**Comment by echosa** [comment]
Awesome. That's helps answer my question. Thanks!
